apiVersion: v1
kind: Service
metadata:
  name: todo-app-backend-svc-production
  namespace: production
spec:
  type: NodePort
  selector:
    app: todo-app
    tier: backend
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - port: 4000
    targetPort: 4000