apiVersion: v1
kind: Service
metadata:
  name: todo-app-frontend-svc-staging
  namespace: staging
spec:
  type: NodePort
  selector:
    app: todo-app-frontend-staging
  ports:
  - port: 3000
    targetPort: 3000
