apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: production
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:3.6.19-xenial
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: mongo-data
            mountPath: /data/db
        resources:
          requests:
            cpu: 300m
            memory: 200Mi
          limits:
            cpu: 600m
            memory: 500Mi
      restartPolicy: Always
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: tier
                  operator: In
                  values:
                  - database
              topologyKey: kubernetes.io/hostname 
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
              claimName: mongo-data 
