apiVersion: v1
kind: Service
metadata:
  name: todo-app-frontend-svc-production
  namespace: production
spec:
  type: NodePort
  selector:
    app: todo-app
    tier: frontend
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - port: 3000
    targetPort: 3000
